Repository Jomalang/ggogit, pull requests merged in 2024-12, with the labels that each got.

#338 Doc: [문서] #336 문서화 컨벤션 정의
  backend-2/doc/usercase/leaf/0_usecase.md
  backend-2/doc/usercase/leaf/1_1 도서 첫 Leaf 생성.md
  docs/.gitignore
  docs/README.md
  docs/문서_컨벤션.md
  docs/유스케이스/파일예시.md
  docs/이미지/컨벤션/로고.png
  ppt/drawio/네트워크_구조도.drawio
Labels: 문서

#346 Docs: [문서] #344 유즈케이스 중간 보고
  backend-2/src/main/resources/application.yml
  docs/유스케이스/파일예시.md
  docs/유즈케이스/유즈케이스.md
Labels: assignee: 조현진, label: 문서, status: 진행중, tag: 유즈케이스

#347 [문서] DTO 스펙 정의 (중간 PR)
  backend-2/convention/ggogit-style.xml
  backend-2/convention/intellij-java-google-style.xml
  docs/API/DTO_변환_정리.md
  docs/API/DTO_스펙.md
  docs/API/V2/AladinController/search/AladinApiSearchCommand.json
  docs/API/V2/AladinController/search/AladinApiSearchResponse.json
  docs/API/V2/BookCategoryController/getBookCategories/ListBookCategoryFilterCommand.json
  docs/API/V2/BookCategoryController/getBookCategories/ListBookCategoryResponse.json
Labels: assignee: 한태규, label: 문서, status: 진행중, position: Planning

#349 [문서] 메인 리드미 작성(중간 PR)
  README.md
  backend-2/src/main/java/io/ggogit/ggogit/config/CorsConfig.java
  backend-2/src/main/resources/application-dev.yml
  backend-2/src/main/resources/data.sql
  docs/이미지/메인리드미/100대램.png
  docs/이미지/메인리드미/기록 방식 예제.png
  docs/이미지/메인리드미/기록방식_리프생성.png
  docs/이미지/메인리드미/기록방식_씨앗생성.png
  docs/이미지/메인리드미/기록방식_트리생성.png
  docs/이미지/메인리드미/기록방식_회고록작성.png
  docs/이미지/메인리드미/사용 언어.png
  docs/이미지/팀원깃헙프로필/Gun-code.png
  docs/이미지/팀원깃헙프로필/Jomalang.png
  docs/이미지/팀원깃헙프로필/TaegyuHan.png
  docs/이미지/팀원깃헙프로필/jjustcodding.png
  docs/이미지/팀원깃헙프로필/pilpearl.png
Labels: assignee: 이희권, label: 문서, status: 진행중, position: Planning

#352 [문서] API URL정의 문서 초안
  docs/API/API_URL_정의.md
Labels: assignee: 조현진, label: 문서, status: 진행중, position: Planning

#353 [문서] #350 코드 컨벤션 및 리드미 멤버 부분 수정
  README.md
  docs/이미지/팀원깃헙프로필/Gun-code.png
  docs/이미지/팀원깃헙프로필/Jomalang.png
  docs/이미지/팀원깃헙프로필/TaegyuHan.png
  docs/이미지/팀원깃헙프로필/jjustcodding.png
  docs/이미지/팀원깃헙프로필/pilpearl.png
  docs/코드_컨벤션_정의/코드_컨벤션_정의.md
Labels: assignee: 이희권, label: 문서

#355 [기능] 리드미 프로필 수정
  README.md
  docs/이미지/팀원깃헙프로필/devCat.png
  docs/이미지/팀원깃헙프로필/eunseoKim.png
  docs/코드_컨벤션_정의/코드_컨벤션_정의.md
Labels: assignee: 이희권, label: 문서, status: 진행중, position: Planning
